version: "3.7"
services:
  ubuntu:
    build:
      context: ./images/ubuntu
    environment:
      TERM: xterm-256color
    stdin_open: true
    container_name: interactive
    volumes:
    - ./:/dotfiles
